#' This function implements the middle-square method to generate pseudo-random numbers in the interval (0,1)
#'
#' @param n length of the generated sequence
#' @param seed The initial seed used to start the algorithm
#'
#' @return Returns a vector of pseudo-random numbers generated by the middle-square method
#'
#' @details
#' This function applies the middle-square algorithm, which consists of squaring the current seed and extracting the central digits to form the next seed. Let \eqn{X_0} be the initial seed with \eqn{d} digits. At each iteration, \eqn{X_i^2} is computed and the middle \eqn{d} digits are extracted to define \eqn{X_{i+1}}. The generated pseudo-random number is obtained as \eqn{U_i = X_i / 10^d}. This process is repeated \eqn{n} times.
#'
#' @examples
#' middleSquare(10, 5497)
#'
#' @export
middleSquare <- function(n, seed){
  replicate(n,{
    square <- seed^2
    d <- nchar(format(seed, scientific = F))
    d2 <- nchar(format(square, scientific = F))

    pi <- ifelse(d%%2==1, (d+1)/2,
                 ifelse(d2%%2==1, d/2, (d/2)+1))
    pf <- pi+d-1

    seed <<- as.numeric(substr(square, pi, pf))
    seed/10^d
  })
}
